services:
  - type: web
    name: odoobot-sql-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app/main.py
    envVars:
      - key: PINECONE_API_KEY
        sync: false
      - key: HUGGINGFACE_API_KEY
        sync: false
